services:
  - type: web
    runtime: static
    name: vexo-tickets
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /media/*
        name: Cache-Control
        value: public, max-age=604800
      - path: /img/*
        name: Cache-Control
        value: public, max-age=604800
